name: enduro
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  percent_indicator: ^4.2.5
  google_fonts: ^6.2.1
  get: ^4.7.2
  path: ^1.9.1
  path_provider: ^2.1.5
  sembast: ^3.8.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/locales/
